lol1

diff --git a/.github/workflows/syntax-check.yml b/.github/workflows/syntax-check.yml
--- a/.github/workflows/syntax-check.yml
+++ b/.github/workflows/syntax-check.yml
@@ -21,34 +21,16 @@ jobs:
       - name: Setup MSBuild
         uses: microsoft/setup-msbuild@v1
 
-      # Проверить директорию
-      - name: Display current directory
-        run: pwd
-
-      # Установить StyleCop.Analyzers
-      - name: Install StyleCop.Analyzers
-        run: nuget install StyleCop.Analyzers -Version 1.2.0-beta.435 -OutputDirectory ./packages
-
-      # Установить FxCopAnalyzers
-      - name: Install FxCopAnalyzers
-        run: nuget install Microsoft.CodeAnalysis.FxCopAnalyzers -Version 3.3.2 -OutputDirectory ./packages
-
-      # Добавить StyleCop и FxCop в проект
-      - name: Add analyzers to project
+      # Проверка структуры проекта
+      - name: Validate .csproj file
         run: |
-          echo '<Project Sdk="Microsoft.NET.Sdk">' > Directory.Build.props
-          echo '  <PropertyGroup>' >> Directory.Build.props
-          echo '    <AnalysisLevel>latest</AnalysisLevel>' >> Directory.Build.props
-          echo '    <EnableNETAnalyzers>true</EnableNETAnalyzers>' >> Directory.Build.props
-          echo '  </PropertyGroup>' >> Directory.Build.props
-          echo '  <ItemGroup>' >> Directory.Build.props
-          echo '    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.435" PrivateAssets="All" />' >> Directory.Build.props
-          echo '    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.2" PrivateAssets="All" />' >> Directory.Build.props
-          echo '  </ItemGroup>' >> Directory.Build.props
-          echo '</Project>' >> Directory.Build.props
+          if not exist "VeterinaryClinic.csproj" (
+            echo "Error: VeterinaryClinic.csproj not found."
+            exit 1
+          )
 
-      # Линтинг кода с помощью StyleCop и FxCop
-      - name: Lint code with StyleCop and FxCop
+      # Линтинг кода с помощью StyleCop
+      - name: Lint code with StyleCop
         run: msbuild "VeterinaryClinic.sln" /p:Configuration=Release /warnaserror
 
       # Сборка проекта
